---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: web-apps.tech
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nasa.9084.bassclarinet@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: nasa.9084.bassclarinet@gmail.com
            apiKeySecretRef:
              name: cloudflare
              key: api-key
