---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hackmd-data
  namespace: hackmd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hackmd-postgres-data
  namespace: hackmd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackmd
  namespace: hackmd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hackmd
  template:
    metadata:
      labels:
        app: hackmd
    spec:
      containers:
        - name: hackmd
          image: hackmdio/hackmd:1.2.0
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: HMD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hackmd-db-password
                  key: postgres-password
            - name: HMD_DB_URL
              value: postgres://hackmd:${HMD_DB_PASSWORD}@localhost:5432/hackmd
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
          readinessProbe:
            httpGet:
              path: /status
              port: 3000
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: hackmd-data
              mountPath: /hackmd/public/uploads
        - name: postgres
          image: postgres:10.5
          ports:
            - protocol: TCP
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: hackmd
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hackmd-db-password
                  key: postgres-password
            - name: POSTGRES_DB
              value: hackmd
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: hackmd-data
          persistentVolumeClaim:
            claimName: hackmd-data
        - name: pg-data
          persistentVolumeClaim:
            claimName: hackmd-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: hackmd
  namespace: hackmd
spec:
  selector:
    app: hackmd
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hackmd
  namespace: hackmd
spec:
  tls:
    - hosts:
        - hackmd.web-apps.tech
  rules:
    - host: hackmd.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: hackmd
              servicePort: 3000
