---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: redmine-backup
  namespace: redmine
spec:
  concurrencyPolicy: Replace
  schedule: '0 0,12 * * *'
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backuper
              image: nasa9084/backup_redmine:18.10.23
              imagePullPolicy: Always
              volumeMounts:
                - name: files
                  mountPath: /usr/src/redmine/files
                  readOnly: true
                - name: plugins
                  mountPath: /usr/src/redmine/plugins
                  readOnly: true
                - name: themes
                  mountPath: /usr/src/redmine/public/themes
                  readOnly: true
              env:
                - name: PGHOST
                  value: postgres
                - name: PGDATABASE
                  value: redmine
                - name: PGUSER
                  value: redmine
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redmine-postgres-password
                      key: password
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: minio_access_key
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: minio_secret_key
          volumes:
            - name: files
              persistentVolumeClaim:
                claimName: redmine-files-pvc
            - name: plugins
              persistentVolumeClaim:
                claimName: redmine-plugins-pvc
            - name: themes
              persistentVolumeClaim:
                claimName: redmine-themes-pvc
