---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-charakoba-cert
  namespace: redmine
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sync-charakoba-cert
  namespace: redmine
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sync-charakoba-cert
  namespace: redmine
roleRef:
  kind: Role
  name: sync-charakoba-cert
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sync-charakoba-cert
    namespace: redmine
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-charakoba-cert
  namespace: redmine
spec:
  concurrencyPolicy: Replace
  schedule: '0 0,12 * * *'
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          serviceAccount: sync-charakoba-cert
          restartPolicy: Never
          containers:
            - name: sync
              image: nasa9084/sync-charakoba-cert:18.08.24
              imagePullPolicy: Always
              env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: minio_access_key
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: minio_secret_key
