---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-files-pvc
  namespace: redmine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-plugins-pvc
  namespace: redmine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-postgresql-pvc
  namespace: redmine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: redmine
spec:
  selector:
    matchLabels:
      app: redmine
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine:3.4.6
          ports:
            - protocol: TCP
              containerPort: 3000
          volumeMounts:
            - name: redmine-files-volume
              mountPath: /usr/src/redmine/files
            - name: redmine-plugins-volume
              mountPath: /usr/src/redmine/plugins
          env:
            - name: REDMINE_DB_POSTGRES
              value: localhost
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmine-postgres-password
                  key: password
            - name: REDMINE_PLUGINS_MIGRATE
              value: 'true'
        - name: postgresql
          image: postgres:10.5
          volumeMounts:
            - name: pg-volume
              mountPath: /var/lib/postgresql/data/pgdata
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: redmine
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmine-postgres-password
                  key: password
      volumes:
        - name: redmine-files-volume
          persistentVolumeClaim:
            claimName: redmine-files-pvc
        - name: redmine-plugins-volume
          persistentVolumeClaim:
            claimName: redmine-plugins-pvc
        - name: pg-volume
          persistentVolumeClaim:
            claimName: redmine-postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redmine
  namespace: redmine
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: redmine
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redmine
  namespace: redmine
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - rm.web-apps.tech
        - rm.charakoba.com
  rules:
    - host: rm.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: redmine
              servicePort: 3000
    - host: rm.charakoba.com
      http:
        paths:
          - path: /
            backend:
              serviceName: redmine
              servicePort: 3000
