---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-pvc
  namespace: redmine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-postgres-pvc
  namespace: redmine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: redmine
spec:
  selector:
    matchLabels:
      app: redmine
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine:3.4.6-passenger
          ports:
            - protocol: TCP
              containerPort: 3000
          volumeMounts:
            - name: redmine-volume
              subPath: files
              mountPath: /usr/src/redmine/files
            - name: redmine-volume
              subPath: plugins
              mountPath: /usr/src/redmine/plugins
            - name: redmine-volume
              subPath: themes
              mountPath: /usr/src/redmine/public/themes
          env:
            - name: REDMINE_DB_POSTGRES
              value: postgres
            - name: REDMINE_DB_USERNAME
              value: redmine
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmine-postgres-password
                  key: password
            - name: REDMINE_PLUGINS_MIGRATE
              value: 'true'
            - name: PASSENGER_MAX_POOL_SIZE
              value: '10'
          readinessProbe:
            httpGet:
              port: 3000
              path: /login
          resources:
            requests:
              memory: 2Gi
            limits:
              memory: 2Gi
      volumes:
        - name: redmine-volume
          persistentVolumeClaim:
            claimName: redmine-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-postgres
  namespace: redmine
spec:
  selector:
    matchLabels:
      app: redmine-postgres
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine-postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:10.5
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-volume
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: redmine
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmine-postgres-password
                  key: password
          resources:
            requests:
              memory: 2Gi
      volumes:
        - name: pg-volume
          persistentVolumeClaim:
            claimName: redmine-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redmine
  namespace: redmine
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: redmine
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: redmine
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: redmine-postgres
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redmine
  namespace: redmine
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - rm.web-apps.tech
    - hosts:
        - rm.charakoba.com
      secretName: rm.charakoba.com
  rules:
    - host: rm.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: redmine
              servicePort: 3000
    - host: rm.charakoba.com
      http:
        paths:
          - path: /
            backend:
              serviceName: redmine
              servicePort: 3000
