---
namespace: prom-system
resources:
  - metadata.yml
  - node_exporter.yml
  - snmp_exporter.yml
  - cadvisor.yml
  - prometheus.yml
  - grafana.yml
configMapGenerator:
  - name: prometheus
    files:
      - config/prometheus.yml
      - config/alert.rules
  - name: snmp
    files:
      - config/snmp.yml
  - name: alertmanager
    files:
      - config/alertmanager.yml
