---
namespace: prom-system
resources:
  - metadata.yml
  - node_exporter.yml
  - snmp_exporter.yml
  - cadvisor.yml
  - prometheus.yml
  - kube_state_metrics.yml
configMapGenerator:
  - name: prometheus
    files:
      - config/prometheus.yml
      - config/alert.rules
  - name: snmp
    files:
      - config/snmp.yml
  - name: alertmanager-config-template
    files:
      - config/alertmanager.yml.tmpl
  - name: alertmanager-confd-toml
    files:
      - config/confd.toml
