---
namespace: prom-system
resources:
  - metadata.yml
  - node_exporter.yml
  - cadvisor.yml
  - prometheus.yml
  - grafana.yml
configMapGenerator:
  - name: prometheus
    files:
      - config/prometheus.yml
