---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: prom-system
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
        exporter: node-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9100'
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v0.18.1
          ports:
            - protocol: TCP
              containerPort: 9100
          args:
            - --collector.systemd
            - --path.rootfs=/host
          volumeMounts:
            - mountPath: /host
              name: root
              readOnly: true
      hostPID: true
      hostNetwork: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: root
          hostPath:
            path: /
