---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: prom-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prom-system
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.3.2
          ports:
            - protocol: TCP
              containerPort: 9090
          args: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus-data", "--storage.tsdb.no-lockfile"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: prometheus-persistent-storage
              mountPath: /prometheus-data
          livenessProbe:
            httpGet:
              port: 9090
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 9090
              path: /-/ready
      volumes:
        - name: config
          configMap:
            name: prometheus
        - name: prometheus-persistent-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prom-system
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: prom-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: prom.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: 9090
