---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: prom-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: prom-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prom-system
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.3.2
          ports:
            - protocol: TCP
              containerPort: 9090
          args: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus-data", "--storage.tsdb.no-lockfile"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-persistent-storage
              mountPath: /prometheus-data
          livenessProbe:
            httpGet:
              port: 9090
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 9090
              path: /-/ready
        - name: alertmanager
          image: prom/alertmanager:v0.15.2
          ports:
            - protocol: TCP
              containerPort: 9093
          args: ["--config.file=/etc/alertmanager/alertmanager.yml", "--storage.path=/alertmanager-data"]
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
          livenessProbe:
            httpGet:
              port: 9093
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 9093
              path: /-/ready
        - name: grafana
          image: grafana/grafana:5.2.2
          env:
            - name: GF_AUTH_BASIC_ENABLED
              value: 'true'
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: 'false'
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: grafana-persistent-storage
              mountPath: /var/lib/grafana
      initContainers:
        - name: init-alertmanager-config
          image: nasa9084/confd:v0.16.0
          imagePullPolicy: Always
          args: ["-onetime", "-backend", "env"]
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
            - name: alertmanager-config-template
              mountPath: /etc/confd/templates
            - name: alertmanager-confd-toml
              mountPath: /etc/confd/conf.d
          env:
            - name: ALERTMANAGER_SLACK_URL
              valueFrom:
                secretKeyRef:
                  name: alertmanager-slack-url
                  key: alertmanager_slack_url
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus
        - name: prometheus-persistent-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: alertmanager-config-template
          configMap:
            name: alertmanager-config-template
        - name: alertmanager-confd-toml
          configMap:
            name: alertmanager-confd-toml
        - name: alertmanager-config
          emptyDir: {}
        - name: grafana-persistent-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prometheus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prom-system
spec:
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
  selector:
    app: prometheus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: prom-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - grafana.web-apps.tech
  rules:
    - host: grafana.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: 3000
