---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: prom-system
spec:
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
        exporter: snmp-exporter
    spec:
      containers:
        - name: snmp-exporter
          image: prom/snmp-exporter:v0.11.0
          ports:
            - protocol: TCP
              containerPort: 9116
          volumeMounts:
            - name: config
              mountPath: /etc/snmp_exporter
      volumes:
        - name: config
          configMap:
            name: snmp
---
apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: prom-sytem
spec:
  selector:
    app: snmp-exporter
  ports:
    - port: 9116
      targetPort: 9116
