---
namespace: falco-system
resources:
  - falco.yml
configMapGenerator:
  - name: falco-config
    files:
      - config/falco.yaml
      - config/application_rules.yml
      - config/falco_rules.yml
      - config/falco_rules_local.yml
