---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ghost-backup
  namespace: ghost
spec:
  concurrencyPolicy: Replace
  schedule: '0 0,12 * * *'
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backuper
              image: nasa9084/backuper:18.08.07
              imagePullPolicy: Always
              volumeMounts:
                - name: target-volume
                  mountPath: /target
                  readOnly: true
              env:
                - name: BACKUP_TARGET
                  value: ghost
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: minio_access_key
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: minio_secret_key
          volumes:
            - name: target-volume
              persistentVolumeClaim:
                claimName: ghost-pvc
