---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: ghost
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:2.1.2
          ports:
            - protocol: TCP
              containerPort: 2368
          volumeMounts:
            - name: ghost-config
              mountPath: /var/lib/ghost/config.production.json
              subPath: config.production.json
            - name: ghost-persistent-storage
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-config
          configMap:
            name: ghost
        - name: ghost-persistent-storage
          persistentVolumeClaim:
            claimName: ghost-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost
spec:
  ports:
    - port: 2368
      targetPort: 2368
  selector:
    app: ghost
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost
  namespace: ghost
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
spec:
  tls:
    - hosts:
        - blog.web-apps.tech
  rules:
    - host: blog.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: ghost
              servicePort: 2368
