---
namespace: ghost
resources:
  - metadata.yml
  - ghost.yml
configMapGenerator:
  - name: ghost-confd-config
    files:
      - config/confd.toml
  - name: ghost-config-template
    files:
      - config/config.production.json.tmpl
