---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-mongodb-data
  namespace: growi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi
  namespace: growi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: growi
  template:
    metadata:
      labels:
        app: growi
    spec:
      containers:
        - name: growi
          image: weseek/growi:3.2.2
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://localhost:27017/growi
            - name: REDIS_URI
              value: redis://localhost:6379/growi
            - name: PASSWORD_SEED
              valueFrom:
                secretKeyRef:
                  name: growi-password-seed
                  key: seed
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
              scheme: HTTP
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        - name: mongodb
          image: mongo:3.6.7
          ports:
            - protocol: TCP
              containerPort: 27017
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
        - name: redis
          image: redis:4.0.11
          ports:
            - protocol: TCP
              containerPort: 6279
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: growi-mongodb-data
---
apiVersion: v1
kind: Service
metadata:
  name: growi
  namespace: growi
spec:
  selector:
    app: growi
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: growi
  namespace: growi
spec:
  tls:
    - hosts:
        - wiki.web-apps.tech
  rules:
    - host: wiki.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: growi
              servicePort: 3000
