---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-mongodb-data
  namespace: growi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-mongodb-configdb
  namespace: growi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-upload-data
  namespace: growi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-elasticsearch-data
  namespace: growi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-elasticsearch-plugin
  namespace: growi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi
  namespace: growi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: growi
  template:
    metadata:
      labels:
        app: growi
    spec:
      containers:
        - name: growi
          image: weseek/growi:3.2.2
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://localhost:27017/growi
            - name: REDIS_URI
              value: redis://localhost:6379/growi
            - name: ELASTICSEARCH_URI
              value: http://localhost:9200/growi
            - name: PASSWORD_SEED
              valueFrom:
                secretKeyRef:
                  name: growi-password-seed
                  key: seed
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
              scheme: HTTP
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: growi-upload-data
              mountPath: /data
        - name: mongodb
          image: mongo:3.6.7
          ports:
            - protocol: TCP
              containerPort: 27017
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: mongodb-configdb
              mountPath: /data/configdb
            - name: mongodb-data
              mountPath: /data/db
        - name: redis
          image: redis:4.0.11
          ports:
            - protocol: TCP
              containerPort: 6279
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
          ports:
            - protocol: TCP
              containerPort: 9200
          env:
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
          command:
            - sh
            - -c
            - "./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || ./bin/elasticsearch-plugin install analysis-kuromoji; ./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu; /usr/share/elasticsearch/bin/es-docker"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-plugin
              mountPath: /usr/share/elasticsearch/plugins
      volumes:
        - name: mongodb-configdb
          persistentVolumeClaim:
            claimName: growi-mongodb-configdb
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: growi-mongodb-data
        - name: growi-upload-data
          persistentVolumeClaim:
            claimName: growi-upload-data
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: growi-elasticsearch-data
        - name: elasticsearch-plugin
          persistentVolumeClaim:
            claimName: growi-elasticsearch-plugin
---
apiVersion: v1
kind: Service
metadata:
  name: growi
  namespace: growi
spec:
  selector:
    app: growi
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: growi
  namespace: growi
spec:
  tls:
    - hosts:
        - wiki.web-apps.tech
  rules:
    - host: wiki.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: growi
              servicePort: 3000
