---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-mongodb-pvc
  namespace: growi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-pvc
  namespace: growi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: growi-elasticsearch-pvc
  namespace: growi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi
  namespace: growi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: growi
  template:
    metadata:
      labels:
        app: growi
    spec:
      containers:
        - name: growi
          image: weseek/growi:3.2.2
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://growi-mongodb:27017/growi
            - name: REDIS_URI
              value: redis://growi-redis:6379/growi
            - name: ELASTICSEARCH_URI
              value: http://growi-elasticsearch:9200/growi
            - name: PASSWORD_SEED
              valueFrom:
                secretKeyRef:
                  name: growi-password-seed
                  key: seed
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
              scheme: HTTP
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: growi-volume
              subPath: data
              mountPath: /data
      volumes:
        - name: growi-volume
          persistentVolumeClaim:
            claimName: growi-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi-mongodb
  namespace: growi
spec:
  selector:
    matchLabels:
      app: growi-mongodb
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: growi-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6.7
          ports:
            - protocol: TCP
              containerPort: 27017
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: mongodb-volume
              subPath: configdb
              mountPath: /data/configdb
            - name: mongodb-volume
              subPath: db
              mountPath: /data/db
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: growi-mongodb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi-redis
  namespace: growi
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: growi-redis
  template:
    metadata:
      labels:
        app: growi-redis
    spec:
      containers:
        - name: redis
          image: redis:4.0.11
          ports:
            - protocol: TCP
              containerPort: 6379
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi-elasticsearch
  namespace: growi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: growi-elasticsearch
  template:
    metadata:
      labels:
        app: growi-elasticsearch
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:1.29.3
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
          ports:
            - protocol: TCP
              containerPort: 9200
          env:
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
          command:
            - sh
            - -c
            - "./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || ./bin/elasticsearch-plugin install analysis-kuromoji; ./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu; /usr/share/elasticsearch/bin/es-docker"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: elasticsearch-volume
              subPath: data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-volume
              subPath: plugins
              mountPath: /usr/share/elasticsearch/plugins
      volumes:
        - name: elasticsearch-volume
          persistentVolumeClaim:
            claimName: growi-elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: growi
  namespace: growi
spec:
  selector:
    app: growi
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: growi-mongodb
  namespace: growi
spec:
  selector:
    app: growi-mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: growi-redis
  namespace: growi
spec:
  selector:
    app: growi-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: growi-elasticsearch
  namespace: growi
spec:
  selector:
    app: growi-elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: growi
  namespace: growi
spec:
  tls:
    - hosts:
        - wiki.web-apps.tech
  rules:
    - host: wiki.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: growi
              servicePort: 3000
