---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: backup-blog-contents-
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: backup-blog-contents
      restartPolicy: OnFailure
      containers:
        - name: backup
          image: nasa9084/backup-blog-contents
          imagePullPolicy: Always
          env:
            - name: GCLOUD_BUCKET_NAME
              value: blog-web-apps-tech-backup
          volumeMounts:
            - name: gcloud-account-key
              mountPath: "/var/run/secrets/cloud.google.com/serviceaccount"
              readOnly: true
      volumes:
        - name: gcloud-account-key
          secret:
            secretName: gcloud-account-key
