---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-blog-contents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-blog-contents
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-blog-contents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-blog-contents
subjects:
  - kind: ServiceAccount
    name: backup-blog-contents
