---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio
  namespace: external-services
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - minio.web-apps.tech
  rules:
    - host: minio.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: minio
              servicePort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: external-services
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio
  namespace: external-services
subsets:
  - addresses:
      - ip: 192.168.1.45
      - ip: 192.168.1.46
      - ip: 192.168.1.47
      - ip: 192.168.1.48
    ports:
      - protocol: TCP
        port: 9000
