---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: external-services
spec:
  type: ExternalName
  externalName: 192.168.1.54
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio
  namespace: external-services
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: minio.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: minio
              servicePort: 9000
