---
apiVersion: v1
kind: Service
metadata:
  name: opennebula
  namespace: external-services
spec:
  type: ExternalName
  externalName: 192.168.1.33
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: opennebula
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: web-apps.tech
spec:
  tls:
    - hosts:
        - one.web-apps.tech
      secretName: one.web-apps.tech-ingress-cert
  rules:
    - host: one.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: opennebula
              servicePort: 9869
