---
apiVersion: v1
kind: Service
metadata:
  name: opennebula
  namespace: external-services
spec:
  type: ExternalName
  externalName: 192.168.1.33
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: opennebula
  namespace: external-services
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - web-apps.tech
      secretName: web-apps.tech
  rules:
    - host: web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: opennebula
              servicePort: 9869
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: web-apps.tech
spec:
  secretName: web-apps.tech
  dnsNames:
    - web-apps.tech
  acme:
    config:
      - domains:
          - web-apps.tech
        dns01:
          provider: cloudflare
  issuerRef:
    name: web-apps.tech
    kind: ClusterIssuer
