---
apiVersion: v1
kind: Service
metadata:
  name: pritunl
  namespace: external-services
spec:
  type: ExternalName
  externalName: 192.168.1.46
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pritunl
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: web-apps.tech
spec:
  tls:
    - hosts:
        - vpn.web-apps.tech
      secretName: vpn.web-apps.tech
  rules:
    - host: vpn.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: pritunl
              servicePort: 80
