---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: external-services
spec:
  type: ExternalName
  externalName: 192.168.1.45
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: web-apps.tech
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  tls:
    - hosts:
        - prometheus.web-apps.tech
      secretName: prometheus.web-apps.tech-ingress-cert
  rules:
    - host: prometheus.web-apps.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: 9090
